jobs:
  destroy:
    name: "Destroy terraform-managed resources"
    runs-on: ubuntu-latest
    if: github.event.inputs.action == 'destroy'
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v4

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        #with:
        #  terraform_version: 1.6.3

      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
